name: Build & Deploy Workflow on merge

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [dev, qa, prod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon Public ECR
        run: |
          aws ecr-public get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin public.ecr.aws

      - name: Get short Git commit SHA
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t public.ecr.aws/${{ secrets.ECR_NAMESPACE }}/${{ secrets.ECR_REPOSITORY }}:${{ env.SHORT_SHA }} ./${{ matrix.env }}-rsingh95

      - name: Push Docker image to ECR
        run: |
          docker push public.ecr.aws/${{ secrets.ECR_NAMESPACE }}/${{ secrets.ECR_REPOSITORY }}:${{ env.SHORT_SHA }}

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Simulate Deploy to Dev
        run: echo "Deploying to Dev..."

  deploy-qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: QA
    steps:
      - name: Simulate Deploy to QA
        run: echo "Deploying to QA..."

  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Prod
    steps:
      - name: Simulate Deploy to Prod
        run: echo "Deploying to Prod..."