name: Main Build & Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [dev, qa, prod]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push to Public ECR
        env:
          ECR_REPO: hu-cicd-${{ github.actor }}-${{ matrix.env }}
        run: |
          docker build -t $ECR_REPO ./${{ matrix.env }}-${{ github.actor }}
          docker tag $ECR_REPO public.ecr.aws/your-ecr-namespace/$ECR_REPO
          docker push public.ecr.aws/your-ecr-namespace/$ECR_REPO

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.actor != '' }} 
    steps:
      - name: Simulate Deploy to Dev
        run: echo "Deploying to Dev..."

  deploy-qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event.inputs.environment == 'qa' }}
    environment:
      name: QA
    steps:
      - name: Simulate Deploy to QA
        run: echo "Deploying to QA..."

  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event.inputs.environment == 'prod' }}
    environment:
      name: Prod
    steps:
      - name: Simulate Deploy to Prod
        run: echo "Deploying to Prod..."