name: PR Build Validation

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'dev-rsingh95/**'
      - 'qa-rsingh95/**'
      - 'prod-rsingh95/**'

jobs:
  build-dev:
    if: contains(github.event.pull_request.labels.*.name, 'dev') || github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t hu-cicd-rsingh95-dev:${{ github.sha }} -f dev-rsingh95/Dockerfile dev-rsingh95/

  build-qa:
    if: contains(github.event.pull_request.labels.*.name, 'qa') || github.event.pull_request.head.ref == 'qa'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t hu-cicd-rsingh95-qa:${{ github.sha }} -f qa-rsingh95/Dockerfile qa-rsingh95/

  build-prod:
    if: contains(github.event.pull_request.labels.*.name, 'prod') || github.event.pull_request.head.ref == 'prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t hu-cicd-rsingh95-prod:${{ github.sha }} -f prod-rsingh95/Dockerfile prod-rsingh95/