name: PR Build Workflow

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  build:
    name: Build Docker Images for All Envs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [dev, qa, prod]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push to Public ECR
        env:
          ECR_NAMESPACE: ${{ secrets.ECR_NAMESPACE }}
        run: |
          IMAGE_NAME=hu-cicd-rsingh95-${{ matrix.env }}
          docker build -t $IMAGE_NAME ./${{ matrix.env }}-rsingh95