name: Build & Deploy Workflow on merge

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [dev, qa, prod]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1

      - name: Build and Push to Public ECR
        env:
          ECR_NAMESPACE: ${{ secrets.ECR_NAMESPACE }}
        run: |
          IMAGE_NAME=hu-cicd-rsingh95-${{ matrix.env }}
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG ./${{ matrix.env }}-rsingh95
          docker tag $IMAGE_NAME:$IMAGE_TAG public.ecr.aws/$ECR_NAMESPACE/$IMAGE_NAME:$IMAGE_TAG
          docker push public.ecr.aws/$ECR_NAMESPACE/$IMAGE_NAME:$IMAGE_TAG

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Simulate Deploy to Dev
        run: echo "Deploying to Dev..."

  deploy-qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: QA
    steps:
      - name: Simulate Deploy to QA
        run: echo "Deploying to QA..."

  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Prod
    steps:
      - name: Simulate Deploy to Prod
        run: echo "Deploying to Prod..."