name: PR Build Workflow

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  build:
    name: Build Docker Images for All Envs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [dev, qa, prod]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push to Public ECR
        env:
          ECR_REPO: hu-cicd-${{ github.actor }}-${{ matrix.env }}
        run: |
          docker build -t $ECR_REPO ./${{ matrix.env }}-${{ github.actor }}