name: Reusable Docker Build and Push Workflow

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: true
      ACCOUNT_ID:
        required: true
      ECR_REPOSITORY:
        required: true

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.get-sha.outputs.short_sha }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get short SHA
      id: get-sha
      run: |
        echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: |
        IMAGE_URI=${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ steps.get-sha.outputs.short_sha }}
        docker build -t $IMAGE_URI .
        docker save $IMAGE_URI > image.tar

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: image.tar

  push-image:
    name: Push Docker Image to ECR
    needs: build-image
    runs-on: ubuntu-latest

    steps:
    - name: Download Docker image artifact
      uses: actions/download-artifact@v4
      with:
        name: docker-image
        path: .

    - name: Load Docker image
      run: docker load < image.tar

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ inputs.aws-region }}

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Push Docker image
      run: |
        SHORT_SHA=${{ needs.build-image.outputs.short_sha }}
        IMAGE_URI=${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$SHORT_SHA
        docker push $IMAGE_URI
