name: Reusable Docker Push

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string
      docker-context:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:
      ECR_NAMESPACE:
      ECR_REPOSITORY:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Amazon Public ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin public.ecr.aws

      - name: Push Docker Image
        run: |
          docker push public.ecr.aws/${{ secrets.ECR_NAMESPACE }}/${{ secrets.ECR_REPOSITORY }}:${{ inputs.image-tag }}