name: Reusable Docker Build

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string
      docker-context:
        required: true
        type: string
    secrets:
      ECR_NAMESPACE:
      ECR_REPOSITORY:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t public.ecr.aws/${{ secrets.ECR_NAMESPACE }}/${{ secrets.ECR_REPOSITORY }}:${{ inputs.image-tag }} ${{ inputs.docker-context }}