name: Reusable Docker Push

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string
      docker-context:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:
      AWS_REGION:
      ACCOUNT_ID:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} |
          docker login --username AWS --password-stdin ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ inputs.docker-context }}:${{ inputs.image-tag }}